# Sounding Data
Radiosondes have been launched from the Grantley Adams International Airport since 1965. The data is accessible via

In [21]:
from datetime import datetime

from siphon.simplewebservice.igra2 import IGRAUpperAir


date = datetime(2000, 7, 18, 12)
dates = [datetime(2000, 7, 18, 0), datetime.now()]
station = 'BBM00078954'

df, header = IGRAUpperAir.request_data(dates, station, derived=True)

df

,pressure,reported_height,calculated_height,temperature,temperature_gradient,potential_temperature,potential_temperature_gradient,virtual_temperature,virtual_potential_temperature,vapor_pressure,saturation_vapor_pressure,reported_relative_humidity,calculated_relative_humidity,relative_humidity_gradient,u_wind,u_wind_gradient,v_wind,v_wind_gradient,refractive_index,date
0,1007.9,47.0,47,300.0,16.7,299.3,25.0,303.4,302.7,30.513,35.395,86.0,86.2,-700.0,-5.1,-4.8,-0.4,1.3,387.0,2000-07-22 00:00:00
1,1006.5,59.0,59,300.2,-8.6,299.6,1.7,303.3,302.8,27.875,35.813,77.2,77.8,-8.6,NaN,NaN,NaN,NaN,376.0,2000-07-22 00:00:00
2,1000.0,117.0,116,299.7,-9.4,299.7,0.2,302.7,302.7,26.876,34.774,77.0,77.3,35.9,NaN,NaN,NaN,NaN,371.0,2000-07-22 00:00:00
3,948.2,585.0,580,295.3,-5.1,299.8,4.7,298.2,302.8,25.123,26.708,94.4,94.1,-49.3,NaN,NaN,NaN,NaN,357.0,2000-07-22 00:00:00
4,925.0,800.0,799,294.2,-3.5,300.8,6.3,296.7,303.4,20.849,24.967,83.4,83.5,-45.2,-8.7,3.7,0.6,-1.3,334.0,2000-07-22 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813265,21.2,NaN,26193,223.9,-2.1,673.6,23.3,223.9,673.6,0.001,0.069,NaN,1.3,0.0,NaN,NaN,NaN,NaN,7.0,2026-09-08 12:00:00
813266,20.0,26570.0,26574,223.1,-2.4,682.4,22.8,223.1,682.4,0.001,0.063,NaN,1.3,-0.3,-4.6,-3.1,5.5,-3.4,7.0,2026-09-08 12:00:00
813267,19.0,NaN,26904,222.3,1.4,690.0,36.5,222.3,690.0,0.001,0.058,NaN,1.2,0.0,NaN,NaN,NaN,NaN,7.0,2026-09-08 12:00:00
813268,13.5,NaN,29143,225.5,-2.0,771.8,26.5,225.5,771.8,0.001,0.083,NaN,1.2,2.0,NaN,NaN,NaN,NaN,5.0,2026-09-08 12:00:00
813269,13.3,NaN,29241,225.3,NaN,774.4,NaN,225.3,774.4,0.001,0.081,NaN,1.4,NaN,-12.9,NaN,-3.5,NaN,5.0,2026-09-08 12:00:00

In [22]:
header

,site_id,year,month,day,hour,release_time,number_levels,precipitable_water,inv_pressure,inv_height,...,lfc_height,lnb_pressure,lnb_height,lifted_index,showalter_index,k_index,total_totals_index,cape,convective_inhibition,date
0,BBM00078954,2000,7,22,0,9060.0,74,39.88,100.65,12.0,...,406.0,113.40,15783.0,-6.0,4.0,28.0,41.0,3823.0,-5.0,2000-07-22 00:00:00
1,BBM00078954,2000,7,22,12,4200.0,67,36.56,NaN,NaN,...,452.0,118.87,15517.0,-6.0,2.0,15.0,42.0,4014.0,-2.0,2000-07-22 12:00:00
2,BBM00078954,2000,7,23,0,9000.0,77,38.14,NaN,NaN,...,838.0,131.22,14929.0,-6.0,2.0,17.0,43.0,3634.0,-14.0,2000-07-23 00:00:00
3,BBM00078954,2000,7,23,12,4200.0,69,35.72,NaN,NaN,...,830.0,130.70,14977.0,-5.0,3.0,15.0,41.0,3263.0,-11.0,2000-07-23 12:00:00
4,BBM00078954,2000,7,24,0,9000.0,57,32.08,NaN,NaN,...,679.0,132.23,14879.0,-4.0,0.0,1.0,43.0,2849.0,-8.0,2000-07-24 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12476,BBM00078954,2026,9,6,12,4200.0,71,46.20,NaN,NaN,...,1107.0,122.92,15386.0,-5.0,0.0,28.0,44.0,3218.0,-8.0,2026-09-06 12:00:00
12477,BBM00078954,2026,9,7,0,9000.0,65,44.22,NaN,NaN,...,800.0,112.99,15919.0,-5.0,1.0,26.0,42.0,3956.0,-3.0,2026-09-07 00:00:00
12478,BBM00078954,2026,9,7,12,4200.0,79,57.71,100.50,35.0,...,1447.0,164.50,13633.0,-4.0,-4.0,38.0,49.0,1140.0,-50.0,2026-09-07 12:00:00
12479,BBM00078954,2026,9,8,0,9000.0,65,46.70,NaN,NaN,...,489.0,103.52,16421.0,-5.0,-1.0,30.0,42.0,4769.0,-5.0,2026-09-08 00:00:00
12480,BBM00078954,2026,9,8,12,4200.0,73,37.35,NaN,NaN,...,1253.0,138.50,14682.0,-3.0,2.0,21.0,41.0,2140.0,-8.0,2026-09-08 12:00:00

In [11]:
import xarray as xr

ds = xr.Dataset(
    data_vars={
        "reported_height": ("pressure", df["reported_height"].values),
        "temperature": ("pressure", df["temperature"].values),
    },
    coords={
        "pressure": df["pressure"].values,
    },
)

In [12]:
ds

<xarray.Dataset> Size: 5kB
Dimensions:          (pressure: 209)
Coordinates:
  * pressure         (pressure) float64 2kB 1.008e+03 1e+03 995.0 ... 12.8 12.3
Data variables:
    reported_height  (pressure) float64 2kB 47.0 113.0 nan nan ... nan nan nan
    temperature      (pressure) float64 2kB 301.4 300.4 300.4 ... 226.9 227.3

In [14]:
df["date"].unique()

<DatetimeArray>
['2020-07-18 00:00:00', '2020-07-18 12:00:00', '2020-07-19 00:00:00',
 '2020-07-19 12:00:00']
Length: 4, dtype: datetime64[ns]

In [23]:
import numpy as np
import xarray as xr

variables = [
    "pressure",
    "reported_height",
    "temperature",
]

times = df["date"].unique()

max_levels = df.groupby("date").size().max()

data = {}

for variable in variables:

    values = np.full(
        (len(times), max_levels),
        np.nan,
    )

    for i, time in enumerate(times):

        sounding = df[df["date"] == time]

        values[i, :len(sounding)] = (
            sounding[variable].values
        )

    data[variable] = (("time", "level"), values)


ds = xr.Dataset(
    data_vars=data,
    coords={
        "time": times,
        "level": np.arange(max_levels),
    },
)

In [24]:
ds

<xarray.Dataset> Size: 52MB
Dimensions:          (time: 12481, level: 172)
Coordinates:
  * time             (time) datetime64[ns] 100kB 2000-07-22 ... 2026-09-08T12...
  * level            (level) int64 1kB 0 1 2 3 4 5 6 ... 166 167 168 169 170 171
Data variables:
    pressure         (time, level) float64 17MB 1.008e+03 1.006e+03 ... nan nan
    reported_height  (time, level) float64 17MB 47.0 59.0 117.0 ... nan nan nan
    temperature      (time, level) float64 17MB 300.0 300.2 299.7 ... nan nan

pandas.core.frame.DataFrame

In [27]:
ds.isel(time=-1).temperature - 273.15

<xarray.DataArray 'temperature' (level: 172)> Size: 1kB
array([ 28.65,  27.05,  26.85,  23.65,  21.85,  17.85,  17.85,  16.85,
        17.05,  12.05,  10.45,  10.05,   8.65,   6.45,   6.65,   2.45,
        -1.05,  -1.85,  -2.85,  -3.65,  -4.85,  -6.85,  -7.65, -10.65,
       -12.65, -15.65, -26.45, -31.05, -32.05, -41.45, -47.25, -50.85,
       -52.65, -53.85, -54.85, -56.25, -57.25, -58.45, -61.65, -65.05,
       -66.05, -69.85, -71.25, -72.25, -76.85, -77.05, -77.25, -77.25,
       -77.25, -77.05, -77.25, -73.45, -70.45, -71.25, -72.25, -61.65,
       -59.25, -53.65, -56.45, -56.45, -56.45, -56.45, -56.25, -56.25,
       -56.25, -55.25, -53.45, -52.05, -49.25, -50.05, -50.85, -47.65,
       -47.85,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
          nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
          nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
          nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
          nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
          nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
          nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
          nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
          nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
          nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
          nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
          nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
          nan,    nan,    nan,    nan])
Coordinates:
  * level    (level) int64 1kB 0 1 2 3 4 5 6 7 ... 165 166 167 168 169 170 171
    time     datetime64[ns] 8B 2026-09-08T12:00:00

In [12]:
from datetime import datetime
from typing import Optional

from metpy.calc import dewpoint_from_relative_humidity
from metpy.units import units
import numpy as np
import pandas as pd
from siphon.simplewebservice.igra2 import IGRAUpperAir
import xarray as xr


def build_request(
    station_id: str,
    start_date: datetime | str,
    end_date: Optional[datetime | str] = None,
    derived: bool = False
) -> tuple[pd.DataFrame, pd.DataFrame]:

    start_date = pd.to_datetime(start_date)

    if end_date is None:
        dates = start_date

    else:
        end_date = pd.to_datetime(end_date)
        dates = [start_date, end_date]

    df, header = IGRAUpperAir.request_data(dates, station_id, derived=derived)

    if df.empty:

        if end_date is None:
            raise ValueError(
                f"No sounding found for station {station_id} "
                f"at {start_date:%Y-%m-%d %H:%M}."
            )

        else:
            raise ValueError(
                f"No soundings found for station {station_id} "
                f"between {start_date:%Y-%m-%d %H:%M} and "
                f"{end_date:%Y-%m-%d %H:%M}."
            )

    return df, header


def build_dataset(
        df: pd.DataFrame,
        header: pd.DataFrame,
)-> xr.Dataset:

    # Get the dates of the individual soundings.
    dates = df["date"].unique()

    # Maximum number of vertical levels in any sounding.
    max_levels = df.groupby('date').size().max()

    # Data variables to include in the dataset.
    data_vars = [
        'pressure',
        'reported_height'
        'calculated_height',
        'temperature',
        'temperature_gradient',
        'dewpoint',
        'dew_point_depression',
        'potential_temperature',
        'potential_temperature_gradient',
        'virtual_temperature',
        'virtual_potential_temperature',
        'wind_dir',
        'wind_speed',
        'u_wind',
        'u_wind_gradient',
        'v_wind',
        'v_wind_gradient',
        'relative_humidity',
        'lvltyp1',
        'lvltyp2',
        'etime',
        'release_time',
        'numlev',
        'latitude',
        'longitude',
        'pressure_source',
        'nonpressure_source',
        'reported_geopotential_height',
        'calculated_geopotential_height',

        'refractive_index',
        'pw',
        'inversion_pressure',
        'inversion_height',
        'mixed_layer_pressure',
        'mixed_layer_height',
        'freezing_pressure',
        'freezing_height',
        'lcl_pressure',
        'lcl_height',
        'lfc_pressure',
        'lfc_height',
        'lnb_pressure',
        'lnb_height',
        'lifted_index',
        'showalter_index',
        'k_index',
        'total_totals_index',
        'cape',
        'cin'
    ]

    return None



# date = datetime(2000, 7, 18, 12)
# dates = [datetime(2000, 7, 18, 0), datetime.now()]
# station = 'BBM00078954'
#
# df, header = IGRAUpperAir.request_data(dates, station, derived=True)
#
# df

df_data, header_data = build_request('BBM00078954', start_date='2020-07-18', end_date='2020-07-20', derived=False)
df_drvd, header_drvd = build_request('BBM00078954', start_date='2020-07-18', end_date='2020-07-20', derived=True)

In [18]:
def build_dataset(
    df_data: pd.DataFrame,
    header_data: pd.DataFrame,
    df_drvd: pd.DataFrame,
    header_drvd: pd.DataFrame,
) -> xr.Dataset:

    # ------------------------------------------------------------
    # Time and level dimensions
    # ------------------------------------------------------------

    times = df_data["date"].unique()

    max_levels = (
        df_data.groupby("date")
        .size()
        .max()
    )

    levels = np.arange(max_levels)

    # ------------------------------------------------------------
    # Variables with vertical levels
    # ------------------------------------------------------------

    profile_variables = {
        "pressure": (df_data, "pressure"),
        "height": (df_data, "height"),
        "temperature": (df_data, "temperature"),
        "dewpoint": (df_data, "dewpoint"),
        "wind_dir": (df_data, "direction"),
        "wind_speed": (df_data, "speed"),
        "relative_humidity": (df_data, "relative_humidity"),
        "lvltyp1": (df_data, "lvltyp1"),
        "lvltyp2": (df_data, "lvltyp2"),
        "etime": (df_data, "etime"),

        "reported_geopotential_height": (
            df_drvd,
            "reported_height",
        ),
        "calculated_geopotential_height": (
            df_drvd,
            "calculated_height",
        ),
        "temperature_gradient": (
            df_drvd,
            "temperature_gradient",
        ),
        "potential_temperature": (
            df_drvd,
            "potential_temperature",
        ),
        "potential_temperature_gradient": (
            df_drvd,
            "potential_temperature_gradient",
        ),
        "virtual_temperature": (
            df_drvd,
            "virtual_temperature",
        ),
        "virtual_potential_temperature": (
            df_drvd,
            "virtual_potential_temperature",
        ),
        "vapor_pressure": (
            df_drvd,
            "vapor_pressure",
        ),
        "saturation_vapor_pressure": (
            df_drvd,
            "saturation_vapor_pressure",
        ),
        "reported_relative_humidity": (
            df_drvd,
            "reported_relative_humidity",
        ),
        "calculated_relative_humidity": (
            df_drvd,
            "calculated_relative_humidity",
        ),
        "relative_humidity_gradient": (
            df_drvd,
            "relative_humidity_gradient",
        ),
        "u_wind": (
            df_drvd,
            "u_wind",
        ),
        "u_wind_gradient": (
            df_drvd,
            "u_wind_gradient",
        ),
        "v_wind": (
            df_drvd,
            "v_wind",
        ),
        "v_wind_gradient": (
            df_drvd,
            "v_wind_gradient",
        ),
        "refractive_index": (
            df_drvd,
            "refractive_index",
        ),
    }

    data_vars = {}

    for name, (df, column) in profile_variables.items():

        values = np.full(
            (len(times), max_levels),
            np.nan,
        )

        for i, time in enumerate(times):

            sounding = df[df["date"] == time]

            nlevels = len(sounding)

            values[i, :nlevels] = sounding[column].values

        data_vars[name] = (
            ("time", "level"),
            values,
        )

    # ------------------------------------------------------------
    # Variables with only a time dimension
    # ------------------------------------------------------------

    sounding_variables = {
        "pw": "precipitable_water",
        "inversion_pressure": "inv_pressure",
        "inversion_height": "inv_height",
        "mixed_layer_pressure": "mixed_layer_pressure",
        "mixed_layer_height": "mixed_layer_height",
        "freezing_pressure": "freezing_point_pressure",
        "freezing_height": "freezing_point_height",
        "lcl_pressure": "lcl_pressure",
        "lcl_height": "lcl_height",
        "lfc_pressure": "lfc_pressure",
        "lfc_height": "lfc_height",
        "lnb_pressure": "lnb_pressure",
        "lnb_height": "lnb_height",
        "lifted_index": "lifted_index",
        "showalter_index": "showalter_index",
        "k_index": "k_index",
        "total_totals_index": "total_totals_index",
        "cape": "cape",
        "cin": "convective_inhibition",
    }

    for name, column in sounding_variables.items():

        values = np.full(len(times), np.nan)

        for i, time in enumerate(times):

            header = header_drvd[
                header_drvd["date"] == time
            ]

            if len(header) > 0:
                values[i] = header.iloc[0][column]

        data_vars[name] = (
            ("time",),
            values,
        )

    # ------------------------------------------------------------
    # Construct Dataset
    # ------------------------------------------------------------

    ds = xr.Dataset(
        data_vars=data_vars,
        coords={
            "time": times,
            "level": levels,
        },
    )

    return ds

ds = build_dataset(
    df_data,
    header_data,
    df_drvd,
    header_drvd,
)

In [19]:
ds

<xarray.Dataset> Size: 143kB
Dimensions:                         (time: 5, level: 131)
Coordinates:
  * time                            (time) datetime64[ns] 40B 2020-07-18 ... ...
  * level                           (level) int64 1kB 0 1 2 3 ... 128 129 130
Data variables: (12/46)
    pressure                        (time, level) float64 5kB 1.008e+03 ... nan
    height                          (time, level) float64 5kB nan 113.0 ... nan
    temperature                     (time, level) float64 5kB 28.2 27.2 ... nan
    dewpoint                        (time, level) float64 5kB 23.2 22.5 ... nan
    wind_dir                        (time, level) float64 5kB 80.0 85.0 ... nan
    wind_speed                      (time, level) float64 5kB 3.6 4.1 ... nan
    ...                              ...
    lifted_index                    (time) float64 40B -4.0 -1.0 -2.0 -3.0 0.0
    showalter_index                 (time) float64 40B 2.0 7.0 3.0 4.0 4.0
    k_index                         (time) float64 40B 24.0 24.0 23.0 19.0 20.0
    total_totals_index              (time) float64 40B 42.0 35.0 39.0 38.0 38.0
    cape                            (time) float64 40B 2.809e+03 ... 689.0
    cin                             (time) float64 40B -3.0 -12.0 0.0 0.0 -22.0

In [14]:
df_data

,lvltyp1,lvltyp2,etime,pressure,pflag,height,zflag,temperature,tflag,relative_humidity,direction,speed,date,u_wind,v_wind,dewpoint
0,2,1,NaN,1008.0,2,NaN,0,28.2,2,NaN,80.0,3.6,2020-07-18,-3.5,-0.6,23.2
1,1,0,NaN,1000.0,0,113.0,2,27.2,2,NaN,85.0,4.1,2020-07-18,-4.1,-0.4,22.5
2,2,0,NaN,995.0,0,NaN,0,27.2,2,NaN,NaN,NaN,2020-07-18,NaN,NaN,22.7
3,2,0,NaN,979.0,0,NaN,0,NaN,0,NaN,85.0,5.1,2020-07-18,-5.1,-0.4,NaN
4,2,0,NaN,950.0,0,NaN,0,23.0,2,NaN,NaN,NaN,2020-07-18,NaN,NaN,20.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,3,0,NaN,NaN,0,25200.0,0,NaN,0,NaN,80.0,15.9,2020-07-20,-15.7,-2.8,NaN
624,3,0,NaN,NaN,0,26700.0,0,NaN,0,NaN,105.0,25.2,2020-07-20,-24.3,6.5,NaN
625,3,0,NaN,NaN,0,27000.0,0,NaN,0,NaN,105.0,28.8,2020-07-20,-27.8,7.5,NaN
626,3,0,NaN,NaN,0,27900.0,0,NaN,0,NaN,80.0,23.7,2020-07-20,-23.3,-4.1,NaN
627,3,0,NaN,NaN,0,30000.0,0,NaN,0,NaN,95.0,21.1,2020-07-20,-21.0,1.8,NaN

In [15]:
header_data

,site_id,year,month,day,hour,release_time,number_levels,pressure_source_code,non_pressure_source_code,latitude,longitude,date
0,BBM00078954,2020,7,18,0,9000,126,ncdc-gts,ncdc-gts,13.0716,-59.4922,2020-07-18 00:00:00
1,BBM00078954,2020,7,18,12,4200,131,ncdc-gts,ncdc-gts,13.0716,-59.4922,2020-07-18 12:00:00
2,BBM00078954,2020,7,19,0,9000,111,ncdc-gts,ncdc-gts,13.0716,-59.4922,2020-07-19 00:00:00
3,BBM00078954,2020,7,19,12,4200,130,ncdc-gts,ncdc-gts,13.0716,-59.4922,2020-07-19 12:00:00
4,BBM00078954,2020,7,20,0,9000,130,ncdc-gts,ncdc-gts,13.0716,-59.4922,2020-07-20 00:00:00

In [16]:
df_drvd

,pressure,reported_height,calculated_height,temperature,temperature_gradient,potential_temperature,potential_temperature_gradient,virtual_temperature,virtual_potential_temperature,vapor_pressure,saturation_vapor_pressure,reported_relative_humidity,calculated_relative_humidity,relative_humidity_gradient,u_wind,u_wind_gradient,v_wind,v_wind_gradient,refractive_index,date
0,1008.0,47.0,47,301.4,-15.2,300.7,-4.5,304.6,303.9,28.558,38.416,NaN,74.3,18.2,-3.5,-9.1,-0.6,3.0,377,2020-07-18
1,1000.0,113.0,117,300.4,0.0,300.4,9.1,303.5,303.5,27.371,36.235,NaN,75.5,22.7,-4.1,-5.2,-0.4,-0.4,372,2020-07-18
2,995.0,NaN,157,300.4,-10.4,300.8,-0.7,303.5,304.0,27.705,36.235,NaN,76.5,27.0,NaN,NaN,NaN,NaN,372,2020-07-18
3,950.0,NaN,561,296.2,-5.0,300.5,4.6,299.1,303.5,24.664,28.209,NaN,87.4,-16.0,NaN,NaN,NaN,NaN,354,2020-07-18
4,925.0,799.0,792,295.0,-5.5,301.6,4.4,297.6,304.3,21.921,26.222,NaN,83.6,-15.2,-7.7,4.5,-0.7,-2.6,337,2020-07-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,20.0,26510.0,26514,221.5,2.6,677.5,40.0,221.5,677.6,0.003,0.053,NaN,6.6,-0.9,-28.4,2.0,5.0,-0.9,7,2020-07-20
259,14.0,NaN,28854,227.7,-1.6,771.3,28.2,227.7,771.4,0.005,0.106,NaN,4.5,-0.3,NaN,NaN,NaN,NaN,5,2020-07-20
260,12.5,NaN,29607,226.5,-0.7,792.5,31.9,226.5,792.6,0.004,0.093,NaN,4.3,0.0,NaN,NaN,NaN,NaN,4,2020-07-20
261,12.0,NaN,29877,226.3,2.4,801.1,42.9,226.3,801.2,0.004,0.091,NaN,4.3,-3.6,NaN,NaN,NaN,NaN,4,2020-07-20
262,11.7,NaN,30045,226.7,NaN,808.3,NaN,226.7,808.4,0.004,0.095,NaN,3.7,NaN,-21.5,NaN,1.9,NaN,4,2020-07-20

In [17]:
header_drvd

,site_id,year,month,day,hour,release_time,number_levels,precipitable_water,inv_pressure,inv_height,...,lfc_height,lnb_pressure,lnb_height,lifted_index,showalter_index,k_index,total_totals_index,cape,convective_inhibition,date
0,BBM00078954,2020,7,18,0,9000,51,43.80,NaN,NaN,...,946,118.25,15606,-4,2,24,42,2809,-3,2020-07-18 00:00:00
1,BBM00078954,2020,7,18,12,4200,53,39.53,NaN,NaN,...,1656,137.58,14710,-1,7,24,35,1931,-12,2020-07-18 12:00:00
2,BBM00078954,2020,7,19,0,9000,51,43.59,NaN,NaN,...,622,113.81,15809,-2,3,23,39,3183,0,2020-07-19 00:00:00
3,BBM00078954,2020,7,19,12,4200,54,34.95,NaN,NaN,...,597,117.41,15621,-3,4,19,38,3383,0,2020-07-19 12:00:00
4,BBM00078954,2020,7,20,0,9000,54,33.88,NaN,NaN,...,1899,173.89,13256,0,4,20,38,689,-22,2020-07-20 00:00:00

In [9]:
df

,lvltyp1,lvltyp2,etime,pressure,pflag,height,zflag,temperature,tflag,relative_humidity,direction,speed,date,u_wind,v_wind,dewpoint
0,2,1,NaN,1008.0,2,NaN,0,28.2,2,NaN,80.0,3.6,2020-07-18,-3.5,-0.6,23.2
1,1,0,NaN,1000.0,0,113.0,2,27.2,2,NaN,85.0,4.1,2020-07-18,-4.1,-0.4,22.5
2,2,0,NaN,995.0,0,NaN,0,27.2,2,NaN,NaN,NaN,2020-07-18,NaN,NaN,22.7
3,2,0,NaN,979.0,0,NaN,0,NaN,0,NaN,85.0,5.1,2020-07-18,-5.1,-0.4,NaN
4,2,0,NaN,950.0,0,NaN,0,23.0,2,NaN,NaN,NaN,2020-07-18,NaN,NaN,20.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,3,0,NaN,NaN,0,25200.0,0,NaN,0,NaN,80.0,15.9,2020-07-20,-15.7,-2.8,NaN
624,3,0,NaN,NaN,0,26700.0,0,NaN,0,NaN,105.0,25.2,2020-07-20,-24.3,6.5,NaN
625,3,0,NaN,NaN,0,27000.0,0,NaN,0,NaN,105.0,28.8,2020-07-20,-27.8,7.5,NaN
626,3,0,NaN,NaN,0,27900.0,0,NaN,0,NaN,80.0,23.7,2020-07-20,-23.3,-4.1,NaN
627,3,0,NaN,NaN,0,30000.0,0,NaN,0,NaN,95.0,21.1,2020-07-20,-21.0,1.8,NaN

In [10]:
header

,site_id,year,month,day,hour,release_time,number_levels,pressure_source_code,non_pressure_source_code,latitude,longitude,date
0,BBM00078954,2020,7,18,0,9000,126,ncdc-gts,ncdc-gts,13.0716,-59.4922,2020-07-18 00:00:00
1,BBM00078954,2020,7,18,12,4200,131,ncdc-gts,ncdc-gts,13.0716,-59.4922,2020-07-18 12:00:00
2,BBM00078954,2020,7,19,0,9000,111,ncdc-gts,ncdc-gts,13.0716,-59.4922,2020-07-19 00:00:00
3,BBM00078954,2020,7,19,12,4200,130,ncdc-gts,ncdc-gts,13.0716,-59.4922,2020-07-19 12:00:00
4,BBM00078954,2020,7,20,0,9000,130,ncdc-gts,ncdc-gts,13.0716,-59.4922,2020-07-20 00:00:00

In [33]:
import pandas as pd

date = "2020-08-10"
date = None

print(pd.Timestamp(date))

NaT

In [ ]:
class SoundingDataset:

    data_vars = [
        'pressure',
        'height',
        'temperature',
        'dewpoint',
        'dew_point_depression',
        'wind_dir',
        'wind_speed',
        'relative_humidity',
        'lvltyp1',
        'lvltyp2',
        'etime',
        'release_time',
        'numlev',
        'latitude',
        'longitude',
        'pressure_source',
        'nonpressure_source',
        'reported_geopotential_height',
        'calculated_geopotential_height',
        'temperature_gradient',
        'potential_temperature',
        'potential_temperature_gradient',
        'virtual_temperature',
        'virtual_potential_temperature',
        'vapor_pressure',
        'saturation_vapor_pressure',
        'reported_relative_humidity',
        'calculated_relative_humidity',
        'relative_humidity_gradient',
        'u_wind',
        'u_wind_gradient',
        'v_wind',
        'v_wind_gradient',
        'refractive_index',
        'pw',
        'inversion_pressure',
        'inversion_height',
        'mixed_layer_pressure',
        'mixed_layer_height',
        'freezing_pressure',
        'freezing_height',
        'lcl_pressure',
        'lcl_height',
        'lfc_pressure',
        'lfc_height',
        'lnb_pressure',
        'lnb_height',
        'lifted_index',
        'showalter_index',
        'k_index',
        'total_totals_index',
        'cape',
        'cin'
    ]

In [ ]:
ds = xr.Dataset(
    data_vars={
        "pressure": (
            ("time", "level"),
            arrays["pressure"],
            {
                "long_name": "air pressure",
                "standard_name": "air_pressure",
                "units": "Pa",
                "description": "Air pressure at the sounding level.",
            },
        ),

        "height": (
            ("time", "level"),
            arrays["height"],
            {
                "long_name": "geopotential height",
                "standard_name": "geopotential_height",
                "units": "m",
                "description": "Geopotential height of the sounding level.",
            },
        ),

        "temperature": (
            ("time", "level"),
            arrays["temperature"],
            {
                "long_name": "air temperature",
                "standard_name": "air_temperature",
                "units": "K",
                "description": "Air temperature at the sounding level.",
            },
        ),

        "dewpoint": (
            ("time", "level"),
            arrays["dewpoint"],
            {
                "long_name": "dew-point temperature",
                "standard_name": "dew_point_temperature",
                "units": "K",
                "description": "Dew-point temperature at the sounding level.",
            },
        ),

        "dew_point_depression": (
            ("time", "level"),
            arrays["dew_point_depression"],
            {
                "long_name": "dew-point depression",
                "units": "K",
                "description": "Difference between air temperature and dew-point temperature."                    ,
            },
        ),

        "wind_dir": (
            ("time", "level"),
            arrays["wind_dir"],
            {
                "long_name": "wind direction",
                "standard_name": "wind_from_direction",
                "units": "degrees",
                "description": (
                    "Direction from which the wind is blowing, "
                    "measured clockwise from true north."
                ),
            },
        ),

        "wind_speed": (
            ("time", "level"),
            arrays["wind_speed"],
            {
                "long_name": "wind speed",
                "standard_name": "wind_speed",
                "units": "m/s",
                "description": "Horizontal wind speed at the sounding level.",
            },
        ),

        "relative_humidity": (
            ("time", "level"),
            arrays["relative_humidity"],
            {
                "long_name": "relative humidity",
                "standard_name": "relative_humidity",
                "units": "%",
                "description": "Relative humidity at the sounding level.",
            },
        ),

        "lvltyp1": (
            ("time", "level"),
            arrays["lvltyp1"],
            {
                "long_name": "primary level type",
                "description": (
                    "IGRA level-type code identifying the primary "
                    "characteristic of the sounding level."
                ),
            },
        ),

        "lvltyp2": (
            ("time", "level"),
            arrays["lvltyp2"],
            {
                "long_name": "secondary level type",
                "description": (
                    "IGRA level-type code identifying the secondary "
                    "characteristic of the sounding level."
                ),
            },
        ),

        "etime": (
            ("time", "level"),
            arrays["etime"],
            {
                "long_name": "elapsed time since launch",
                "units": "s",
                "description": (
                    "Elapsed time from radiosonde launch to the "
                    "observation at the sounding level."
                ),
            },
        ),

        # Per-sounding variables

        "release_time": (
            "time",
            release_time,
            {
                "long_name": "release time",
                "units": "minutes",
                "description": (
                    "Time of radiosonde release relative to "
                    "the nominal sounding time."
                ),
            },
        ),

        "numlev": (
            "time",
            numlev,
            {
                "long_name": "number of levels",
                "units": "1",
                "description": "Number of reported levels in the sounding."
            },
        ),

        "latitude": (
            "time",
            lat,
            {
                "long_name": "station latitude",
                "standard_name": "latitude",
                "units": "degrees_north",
            },
        ),

        "longitude": (
            "time",
            lon,
            {
                "long_name": "station longitude",
                "standard_name": "longitude",
                "units": "degrees_east",
            },
        ),

        "pressure_source": (
            "time",
            np.asarray(p_src, dtype="U16"),
            {
                "long_name": "pressure source",
                "description": "IGRA source code for pressure observations.",
            },
        ),

        "nonpressure_source": (
            "time",
            np.asarray(np_src, dtype="U16"),
            {
                "long_name": "non-pressure source",
                "description": "IGRA source code for non-pressure observations."
            },
        ),
    },
    coords={
        "time": pd.to_datetime(times),
        "level": np.arange(max_levels),
    },
    attrs={
        "source": "NOAA NCEI Integrated Global Radiosonde Archive (IGRA Version 2)",
        "institution": "NOAA National Centers for Environmental Information",
        "title": "IGRA Radiosonde Profiles",
        "history": (
            f"Converted from IGRA text format on "
            f"{pd.Timestamp.now().strftime('%Y-%m-%d %H:%M UTC')}"
        ),
        "references": (
            "https://www.ncei.noaa.gov/products/weather-balloon/integrated-global-radiosonde-archive"
            "integrated-global-radiosonde-archive"
        ),
        "featureType": "timeSeriesProfile",
    },
)

ds.attrs.update(attrs_dict)
ds.attrs['station_name'] = ds.attrs['station_name'].title()
ds.attrs['elevation_units'] = 'm'

In [4]:
df['pressure']

0      1008.0
1      1000.0
2       995.0
3       950.0
4       925.0
        ...
258      20.0
259      14.0
260      12.5
261      12.0
262      11.7
Name: pressure, Length: 263, dtype: float64

In [5]:
from datetime import datetime
from typing import Optional

import numpy as np
import pandas as pd
from siphon.simplewebservice.igra2 import IGRAUpperAir
import xarray as xr


def build_request(
    station_id: str,
    start_date: datetime | str,
    end_date: Optional[datetime | str] = None,
    derived: bool = False
) -> tuple[pd.DataFrame, pd.DataFrame]:

    start_date = pd.to_datetime(start_date)

    if end_date is None:
        dates = start_date

    else:
        end_date = pd.to_datetime(end_date)
        dates = [start_date, end_date]

    df, header = IGRAUpperAir.request_data(
        dates,
        station_id,
        derived=derived
    )

    if df.empty:

        if end_date is None:
            raise ValueError(
                f"No sounding found for station {station_id} "
                f"at {start_date:%Y-%m-%d %H:%M}."
            )

        else:
            raise ValueError(
                f"No soundings found for station {station_id} "
                f"between {start_date:%Y-%m-%d %H:%M} and "
                f"{end_date:%Y-%m-%d %H:%M}."
            )

    return df, header


def build_dataset(
    df: pd.DataFrame,
    header: pd.DataFrame,
) -> xr.Dataset:

    # Get the dates of the individual soundings
    dates = df["date"].unique()

    # Maximum number of vertical levels in any sounding
    max_levels = df.groupby("date").size().max()

    # Variables to include in the Dataset
    variables = [
        "pressure",
        "reported_height",
        "temperature",
    ]

    data = {}

    for variable in variables:

        values = np.full(
            (len(dates), max_levels),
            np.nan,
        )

        for i, date in enumerate(dates):

            sounding = df[df["date"] == date]

            values[i, :len(sounding)] = (
                sounding[variable].values
            )

        data[variable] = (
            ("date", "level"),
            values,
        )

    ds = xr.Dataset(
        data_vars=data,
        coords={
            "date": dates,
            "level": np.arange(max_levels),
        },
    )

    return ds

In [6]:
df, header = build_request(
    "BBM00078954",
    start_date="2020-07-18",
    end_date="2020-07-20",
    derived=True,
)

ds = build_dataset(df, header)

print(ds)

<xarray.Dataset> Size: 7kB
Dimensions:          (date: 5, level: 54)
Coordinates:
  * date             (date) datetime64[ns] 40B 2020-07-18 ... 2020-07-20
  * level            (level) int64 432B 0 1 2 3 4 5 6 7 ... 47 48 49 50 51 52 53
Data variables:
    pressure         (date, level) float64 2kB 1.008e+03 1e+03 ... 12.0 11.7
    reported_height  (date, level) float64 2kB 47.0 113.0 nan ... nan nan nan
    temperature      (date, level) float64 2kB 301.4 300.4 300.4 ... 226.3 226.7

In [7]:
ds

<xarray.Dataset> Size: 7kB
Dimensions:          (date: 5, level: 54)
Coordinates:
  * date             (date) datetime64[ns] 40B 2020-07-18 ... 2020-07-20
  * level            (level) int64 432B 0 1 2 3 4 5 6 7 ... 47 48 49 50 51 52 53
Data variables:
    pressure         (date, level) float64 2kB 1.008e+03 1e+03 ... 12.0 11.7
    reported_height  (date, level) float64 2kB 47.0 113.0 nan ... nan nan nan
    temperature      (date, level) float64 2kB 301.4 300.4 300.4 ... 226.3 226.7

In [11]:
from datetime import datetime
from typing import Optional

import numpy as np
import pandas as pd
from siphon.simplewebservice.igra2 import IGRAUpperAir
import xarray as xr

from src.sif.observations.igra2_requests import igra2_stations_df


def build_request(
    station_id: str,
    start_date: datetime | str,
    end_date: Optional[datetime | str] = None,
    derived: bool = False
) -> tuple[pd.DataFrame, pd.DataFrame]:

    start_date = pd.to_datetime(start_date)

    if end_date is None:
        dates = start_date

    else:
        end_date = pd.to_datetime(end_date)
        dates = [start_date, end_date]

    df, header = IGRAUpperAir.request_data(
        dates,
        station_id,
        derived=derived
    )

    if df.empty:

        if end_date is None:
            raise ValueError(
                f"No sounding found for station {station_id} "
                f"at {start_date:%Y-%m-%d %H:%M}."
            )

        else:
            raise ValueError(
                f"No soundings found for station {station_id} "
                f"between {start_date:%Y-%m-%d %H:%M} and "
                f"{end_date:%Y-%m-%d %H:%M}."
            )

    return df, header


def data_dataset(
    df_data: pd.DataFrame,
    header_data: pd.DataFrame
) -> xr.Dataset:
    """
    Convert non-derived IGRA sounding data into an xarray Dataset.

    Parameters
    ----------
    df_data : pd.DataFrame
        IGRA sounding data returned by Siphon with derived=False.

    header_data : pd.DataFrame
        IGRA sounding header data.

    Returns
    -------
    xr.Dataset
        xarray Dataset containing the reported IGRA sounding profiles.
    """

    # Time and level dimensions.
    times = sorted(df_data["date"].unique())
    ntime = len(times)

    max_levels = df_data.groupby("date").size().max()
    levels = np.arange(max_levels)

    # Variables with vertical levels.
    profile_vars = [
        "pressure",
        "height",
        "temperature",
        "dewpoint",
        "relative_humidity",
        "direction",
        "speed",
        "lvltyp1",
        "lvltyp2",
        "etime",
    ]

    # Initialize arrays for profile variables with NaN values.
    arrays = {
        var: np.full((ntime, max_levels), np.nan)
        for var in profile_vars
    }

    # Per-sounding variables.
    release_time = np.full(ntime, np.nan)
    numlev = np.full(ntime, np.nan)
    lat = np.full(ntime, np.nan)
    lon = np.full(ntime, np.nan)

    p_src = []
    np_src = []

    # Loop through soundings.
    for i, time in enumerate(times):

        sounding = df_data[df_data["date"] == time]

        n = len(sounding)

        # Fill profile arrays.
        for var in profile_vars:

            if var in sounding.columns:
                arrays[var][i, :n] = sounding[var].values

        # Get header information for this sounding.
        header = header_data[header_data["date"] == time]

        if len(header) > 0:

            header = header.iloc[0]


            lat[i] = header["latitude"]
            lon[i] = header["longitude"]

            p_src.append(header["pressure_source"])
            np_src.append(header["nonpressure_source"])

        else:

            release_time[i] = np.nan
            numlev[i] = np.nan

            lat[i] = np.nan
            lon[i] = np.nan

            p_src.append("")
            np_src.append("")

    # Get station attributes.
    station_id = header_data.iloc[0]["station"]

    station_df = igra2_stations_df()

    attrs_dict = (
        station_df.loc[
            station_df["station_id"] == station_id
        ]
        .reset_index(drop=True)
        .iloc[0]
        .to_dict()
    )

    # Construct Dataset.
    ds = xr.Dataset(
        data_vars={

            "pressure": (
                ("time", "level"),
                arrays["pressure"],
                {
                    "long_name": "air pressure",
                    "standard_name": "air_pressure",
                    "units": "hPa",
                    "description": (
                        "Air pressure at the sounding level."
                    ),
                },
            ),

            "height": (
                ("time", "level"),
                arrays["height"],
                {
                    "long_name": "geopotential height",
                    "standard_name": "geopotential_height",
                    "units": "m",
                    "description": (
                        "Geopotential height of the sounding level."
                    ),
                },
            ),

            "temperature": (
                ("time", "level"),
                arrays["temperature"],
                {
                    "long_name": "air temperature",
                    "standard_name": "air_temperature",
                    "units": "degC",
                    "description": (
                        "Air temperature at the sounding level."
                    ),
                },
            ),

            "dewpoint": (
                ("time", "level"),
                arrays["dewpoint"],
                {
                    "long_name": "dew-point temperature",
                    "standard_name": "dew_point_temperature",
                    "units": "degC",
                    "description": (
                        "Dew-point temperature at the sounding level."
                    ),
                },
            ),

            "wind_dir": (
                ("time", "level"),
                arrays["direction"],
                {
                    "long_name": "wind direction",
                    "standard_name": "wind_from_direction",
                    "units": "degrees",
                    "description": (
                        "Direction from which the wind is blowing, "
                        "measured clockwise from true north."
                    ),
                },
            ),

            "wind_speed": (
                ("time", "level"),
                arrays["speed"],
                {
                    "long_name": "wind speed",
                    "standard_name": "wind_speed",
                    "units": "m/s",
                    "description": (
                        "Horizontal wind speed at the sounding level."
                    ),
                },
            ),

            "relative_humidity": (
                ("time", "level"),
                arrays["relative_humidity"],
                {
                    "long_name": "relative humidity",
                    "standard_name": "relative_humidity",
                    "units": "%",
                    "description": (
                        "Relative humidity at the sounding level."
                    ),
                },
            ),

            "lvltyp1": (
                ("time", "level"),
                arrays["lvltyp1"],
                {
                    "long_name": "primary level type",
                    "description": (
                        "IGRA primary level-type code."
                    ),
                },
            ),

            "lvltyp2": (
                ("time", "level"),
                arrays["lvltyp2"],
                {
                    "long_name": "secondary level type",
                    "description": (
                        "IGRA secondary level-type code."
                    ),
                },
            ),

            "etime": (
                ("time", "level"),
                arrays["etime"],
                {
                    "long_name": "elapsed time since launch",
                    "units": "s",
                    "description": (
                        "Elapsed time from radiosonde launch to "
                        "the observation at the sounding level."
                    ),
                },
            ),

            # Per-sounding variables.

            "release_time": (
                "time",
                release_time,
                {
                    "long_name": "release time",
                    "units": "minutes",
                    "description": (
                        "Time of radiosonde release relative to "
                        "the nominal sounding time."
                    ),
                },
            ),

            "numlev": (
                "time",
                numlev,
                {
                    "long_name": "number of levels",
                    "units": "1",
                    "description": (
                        "Number of reported levels in the sounding."
                    ),
                },
            ),

            "latitude": (
                "time",
                lat,
                {
                    "long_name": "station latitude",
                    "standard_name": "latitude",
                    "units": "degrees_north",
                },
            ),

            "longitude": (
                "time",
                lon,
                {
                    "long_name": "station longitude",
                    "standard_name": "longitude",
                    "units": "degrees_east",
                },
            ),

            "pressure_source": (
                "time",
                np.asarray(p_src, dtype="U16"),
                {
                    "long_name": "pressure source",
                    "description": (
                        "IGRA source code for pressure observations."
                    ),
                },
            ),

            "nonpressure_source": (
                "time",
                np.asarray(np_src, dtype="U16"),
                {
                    "long_name": "non-pressure source",
                    "description": (
                        "IGRA source code for non-pressure observations."
                    ),
                },
            ),
        },

        coords={
            "time": pd.to_datetime(times),
            "level": levels,
        },

        attrs={
            "source": (
                "NOAA NCEI Integrated Global Radiosonde Archive "
                "(IGRA Version 2)"
            ),
            "institution": (
                "NOAA National Centers for Environmental Information"
            ),
            "title": "IGRA Radiosonde Profiles",
            "history": (
                f"Converted from IGRA data using Siphon on "
                f"{pd.Timestamp.now().strftime('%Y-%m-%d %H:%M UTC')}"
            ),
            "references": (
                "https://www.ncei.noaa.gov/products/weather-balloon/"
                "integrated-global-radiosonde-archive"
            ),
            "featureType": "timeSeriesProfile",
        },
    )

    # Add station metadata.
    ds.attrs.update(attrs_dict)

    ds.attrs["station_name"] = (
        ds.attrs["station_name"].title()
    )

    ds.attrs["elevation_units"] = "m"

    return ds

In [12]:
df, header = build_request(
    "BBM00078954",
    start_date="2020-07-18",
    end_date="2020-07-20",
    derived=False
)

ds = data_dataset(df, header)

KeyError: 'pressure_source'

In [8]:
from datetime import datetime
from typing import Optional

import numpy as np
import pandas as pd
from siphon.simplewebservice.igra2 import IGRAUpperAir
import xarray as xr

from src.sif.observations.igra2_requests import igra2_stations_df


def build_request(
    station_id: str,
    start_date: datetime | str,
    end_date: Optional[datetime | str] = None,
    derived: bool = False
) -> tuple[pd.DataFrame, pd.DataFrame]:

    start_date = pd.to_datetime(start_date)

    if end_date is None:
        dates = start_date

    else:
        end_date = pd.to_datetime(end_date)
        dates = [start_date, end_date]

    df, header = IGRAUpperAir.request_data(
        dates,
        station_id,
        derived=derived
    )

    if df.empty:

        if end_date is None:
            raise ValueError(
                f"No sounding found for station {station_id} "
                f"at {start_date:%Y-%m-%d %H:%M}."
            )

        else:
            raise ValueError(
                f"No soundings found for station {station_id} "
                f"between {start_date:%Y-%m-%d %H:%M} and "
                f"{end_date:%Y-%m-%d %H:%M}."
            )

    return df, header


def data_dataset(
    df_data: pd.DataFrame,
    header_data: pd.DataFrame
) \
        -> xr.Dataset:
    """
    Convert non-derived IGRA sounding data into an xarray Dataset.

    Parameters
        df_data : pd.DataFrame
            IGRA sounding data returned by Siphon with derived=False.

        header_data : pd.DataFrame
            IGRA sounding header data.

    Returns
        xr.Dataset
            xarray Dataset containing the reported IGRA sounding profiles.
    """

    # Time and level dimensions.
    times = sorted(df_data["date"].unique())
    ntime = len(times)

    max_levels = df_data.groupby("date").size().max()
    levels = np.arange(max_levels)

    # Variables with vertical levels.
    profile_vars = [
        "pressure",
        "height",
        "temperature",
        "dewpoint",
        "relative_humidity",
        "direction",
        "speed",
        "lvltyp1",
        "lvltyp2",
        "etime",
    ]

    # Initialize arrays for profile variables with NaN values.
    arrays = {var: np.full((ntime, max_levels), np.nan) for var in profile_vars}

    # Loop through soundings.
    for i, time in enumerate(times):

        sounding = df_data[df_data["date"] == time]
        n = len(sounding)

        for var in sounding.columns:
            arrays[var][i, :n] = sounding[var].values

    # Header data
    header_data = header_data.copy()
    header_data["date"] = pd.to_datetime(header_data["date"])

    # Initialize header variables.
    header_vars = {}

    # Loop through the columns in the header.
    for var in header_data.columns:

        # Do not include the date column as a data variable.
        if var == "date":
            continue

        # Create one value for each sounding.
        values = np.full(ntime, np.nan)

        for i, time in enumerate(times):

            header = header_data[header_data["date"] == time]

            if len(header) > 0:

                values[i] = header.iloc[0][var]

        header_vars[var] = values

    # ------------------------------------------------------------
    # Construct Dataset
    # ------------------------------------------------------------

    ds = xr.Dataset(
        data_vars={

            "pressure": (
                ("time", "level"),
                arrays["pressure"],
                {
                    "long_name": "air pressure",
                    "standard_name": "air_pressure",
                    "units": "hPa",
                    "description": (
                        "Air pressure at the sounding level."
                    ),
                },
            ),

            "height": (
                ("time", "level"),
                arrays["height"],
                {
                    "long_name": "geopotential height",
                    "standard_name": "geopotential_height",
                    "units": "m",
                    "description": (
                        "Geopotential height of the sounding level."
                    ),
                },
            ),

            "temperature": (
                ("time", "level"),
                arrays["temperature"],
                {
                    "long_name": "air temperature",
                    "standard_name": "air_temperature",
                    "units": "degC",
                    "description": (
                        "Air temperature at the sounding level."
                    ),
                },
            ),

            "dewpoint": (
                ("time", "level"),
                arrays["dewpoint"],
                {
                    "long_name": "dew-point temperature",
                    "standard_name": "dew_point_temperature",
                    "units": "degC",
                    "description": (
                        "Dew-point temperature at the sounding level."
                    ),
                },
            ),

            "wind_dir": (
                ("time", "level"),
                arrays["direction"],
                {
                    "long_name": "wind direction",
                    "standard_name": "wind_from_direction",
                    "units": "degrees",
                    "description": (
                        "Direction from which the wind is blowing."
                    ),
                },
            ),

            "wind_speed": (
                ("time", "level"),
                arrays["speed"],
                {
                    "long_name": "wind speed",
                    "standard_name": "wind_speed",
                    "units": "m/s",
                    "description": (
                        "Horizontal wind speed at the sounding level."
                    ),
                },
            ),

            "relative_humidity": (
                ("time", "level"),
                arrays["relative_humidity"],
                {
                    "long_name": "relative humidity",
                    "standard_name": "relative_humidity",
                    "units": "%",
                    "description": (
                        "Relative humidity at the sounding level."
                    ),
                },
            ),

            "lvltyp1": (
                ("time", "level"),
                arrays["lvltyp1"],
                {
                    "long_name": "primary level type",
                    "description": (
                        "IGRA primary level-type code."
                    ),
                },
            ),

            "lvltyp2": (
                ("time", "level"),
                arrays["lvltyp2"],
                {
                    "long_name": "secondary level type",
                    "description": (
                        "IGRA secondary level-type code."
                    ),
                },
            ),

            "etime": (
                ("time", "level"),
                arrays["etime"],
                {
                    "long_name": "elapsed time since launch",
                    "units": "s",
                    "description": (
                        "Elapsed time from radiosonde launch."
                    ),
                },
            ),

            "numlev": (
                "time",
                numlev,
                {
                    "long_name": "number of levels",
                    "units": "1",
                    "description": (
                        "Number of vertical levels in the sounding."
                    ),
                },
            ),
        },

        coords={
            "time": pd.to_datetime(times),
            "level": levels,
        },

        attrs={
            "source": (
                "NOAA NCEI Integrated Global Radiosonde Archive "
                "(IGRA Version 2)"
            ),
            "institution": (
                "NOAA National Centers for Environmental Information"
            ),
            "title": "IGRA Radiosonde Profiles",
            "history": (
                "Converted from IGRA data using Siphon on "
                f"{pd.Timestamp.now().strftime('%Y-%m-%d %H:%M UTC')}"
            ),
            "references": (
                "https://www.ncei.noaa.gov/products/weather-balloon/"
                "integrated-global-radiosonde-archive"
            ),
            "featureType": "timeSeriesProfile",
        },
    )

    # Add header variables to the Dataset.
    for var, values in header_vars.items():

        # Only add variables that are numeric.
        if np.issubdtype(values.dtype, np.number):

            ds[var] = (
                "time",
                values,
            )

    return ds

In [4]:
df, header = build_request(
    "BBM00078954",
    start_date="2020-07-18",
    end_date="2020-07-20",
    derived=False
)

ds = data_dataset(df, header)

In [5]:
ds

<xarray.Dataset> Size: 80kB
Dimensions:                   (time: 5, level: 131)
Coordinates:
  * time                      (time) datetime64[ns] 40B 2020-07-18 ... 2020-0...
  * level                     (level) int64 1kB 0 1 2 3 4 ... 127 128 129 130
Data variables: (12/19)
    lvltyp1                   (time, level) float64 5kB 2.0 1.0 2.0 ... 3.0 nan
    lvltyp2                   (time, level) float64 5kB 1.0 0.0 0.0 ... 0.0 nan
    etime                     (time, level) float64 5kB nan nan nan ... nan nan
    pressure                  (time, level) float64 5kB 1.008e+03 1e+03 ... nan
    pflag                     (time, level) float64 5kB 2.0 0.0 0.0 ... 0.0 nan
    height                    (time, level) float64 5kB nan 113.0 ... 3e+04 nan
    ...                        ...
    v_wind                    (time, level) float64 5kB -0.6 -0.4 ... 1.8 nan
    dewpoint                  (time, level) float64 5kB 23.2 22.5 ... nan nan
    release_time              (time) int64 40B 9000 4200 9000 4200 9000
    number_levels             (time) int64 40B 126 131 111 130 130
    pressure_source_code      (time) object 40B 'ncdc-gts' ... 'ncdc-gts'
    non_pressure_source_code  (time) object 40B 'ncdc-gts' ... 'ncdc-gts'

In [6]:
from datetime import datetime
from typing import Optional

import numpy as np
import pandas as pd
from siphon.simplewebservice.igra2 import IGRAUpperAir
import xarray as xr

from src.sif.observations.igra2_requests import igra2_stations_df


def build_request(
    station_id: str,
    start_date: datetime | str,
    end_date: Optional[datetime | str] = None,
    derived: bool = False
) -> tuple[pd.DataFrame, pd.DataFrame]:

    start_date = pd.to_datetime(start_date)

    if end_date is None:
        dates = start_date

    else:
        end_date = pd.to_datetime(end_date)
        dates = [start_date, end_date]

    df, header = IGRAUpperAir.request_data(
        dates,
        station_id,
        derived=derived
    )

    if df.empty:

        if end_date is None:
            raise ValueError(
                f"No sounding found for station {station_id} "
                f"at {start_date:%Y-%m-%d %H:%M}."
            )

        else:
            raise ValueError(
                f"No soundings found for station {station_id} "
                f"between {start_date:%Y-%m-%d %H:%M} and "
                f"{end_date:%Y-%m-%d %H:%M}."
            )

    return df, header

def data_dataset(
    df_data: pd.DataFrame,
    header_data: pd.DataFrame
) -> xr.Dataset:


    # Time and vertical levels.
    times = sorted(df_data["date"].unique())
    ntime = len(times)

    max_levels = df_data.groupby("date").size().max()
    levels = np.arange(max_levels)

    # Profile data: (time, level).
    profile_vars = [
        "lvltyp1",
        "lvltyp2",
        "etime",
        "pressure",
        "pflag",
        "height",
        "zflag",
        "temperature",
        "tflag",
        "relative_humidity",
        "direction",
        "speed",
        "u_wind",
        "v_wind",
        "dewpoint",
    ]

    arrays = {
        var: np.full((ntime, max_levels), np.nan)
        for var in profile_vars
    }

    for i, time in enumerate(times):

        sounding = df_data[df_data["date"] == time]
        n = len(sounding)

        for var in profile_vars:
            arrays[var][i, :n] = sounding[var].values

    # Header data: (time,)
    header_data = header_data.copy()

    header_data = (
        header_data
        .set_index("date")
        .reindex(pd.to_datetime(times))
    )

    header_data.index.name = "time"

    header_ds = xr.Dataset.from_dataframe(header_data)


    # Create profile Dataset.
    ds = xr.Dataset(
        data_vars={
            "pressure": (
                ("time", "level"),
                arrays["pressure"],
                {
                    "long_name": "air pressure",
                    "standard_name": "air_pressure",
                    "units": "Pa",
                    "description": "Air pressure at the sounding level.",
                },
            ),

            "height": (
                ("time", "level"),
                arrays["height"],
                {
                    "long_name": "geopotential height",
                    "standard_name": "geopotential_height",
                    "units": "m",
                    "description": "Geopotential height of the sounding level.",
                },
            ),

            "temperature": (
                ("time", "level"),
                arrays["temperature"],
                {
                    "long_name": "air temperature",
                    "standard_name": "air_temperature",
                    "units": "K",
                    "description": "Air temperature at the sounding level.",
                },
            ),

            "dewpoint": (
                ("time", "level"),
                arrays["dewpoint"],
                {
                    "long_name": "dew-point temperature",
                    "standard_name": "dew_point_temperature",
                    "units": "K",
                    "description": "Dew-point temperature at the sounding level.",
                },
            ),

            "dew_point_depression": (
                ("time", "level"),
                arrays["dew_point_depression"],
                {
                    "long_name": "dew-point depression",
                    "units": "K",
                    "description": "Difference between air temperature and dew-point temperature."                    ,
                },
            ),

            "wind_dir": (
                ("time", "level"),
                arrays["wind_dir"],
                {
                    "long_name": "wind direction",
                    "standard_name": "wind_from_direction",
                    "units": "degrees",
                    "description": (
                        "Direction from which the wind is blowing, "
                        "measured clockwise from true north."
                    ),
                },
            ),

            "wind_speed": (
                ("time", "level"),
                arrays["wind_speed"],
                {
                    "long_name": "wind speed",
                    "standard_name": "wind_speed",
                    "units": "m/s",
                    "description": "Horizontal wind speed at the sounding level.",
                },
            ),

            "relative_humidity": (
                ("time", "level"),
                arrays["relative_humidity"],
                {
                    "long_name": "relative humidity",
                    "standard_name": "relative_humidity",
                    "units": "%",
                    "description": "Relative humidity at the sounding level.",
                },
            ),

            "lvltyp1": (
                ("time", "level"),
                arrays["lvltyp1"],
                {
                    "long_name": "primary level type",
                    "description": (
                        "IGRA level-type code identifying the primary "
                        "characteristic of the sounding level."
                    ),
                },
            ),

            "lvltyp2": (
                ("time", "level"),
                arrays["lvltyp2"],
                {
                    "long_name": "secondary level type",
                    "description": (
                        "IGRA level-type code identifying the secondary "
                        "characteristic of the sounding level."
                    ),
                },
            ),

            "etime": (
                ("time", "level"),
                arrays["etime"],
                {
                    "long_name": "elapsed time since launch",
                    "units": "s",
                    "description": (
                        "Elapsed time from radiosonde launch to the "
                        "observation at the sounding level."
                    ),
                },
            ),

            # Per-sounding variables
            "release_time": (
                "time",
                release_time,
                {
                    "long_name": "release time",
                    "units": "minutes",
                    "description": (
                        "Time of radiosonde release relative to "
                        "the nominal sounding time."
                    ),
                },
            ),

            "numlev": (
                "time",
                numlev,
                {
                    "long_name": "number of levels",
                    "units": "1",
                    "description": "Number of reported levels in the sounding."
                },
            ),

            "latitude": (
                "time",
                lat,
                {
                    "long_name": "station latitude",
                    "standard_name": "latitude",
                    "units": "degrees_north",
                },
            ),

            "longitude": (
                "time",
                lon,
                {
                    "long_name": "station longitude",
                    "standard_name": "longitude",
                    "units": "degrees_east",
                },
            ),

            "pressure_source": (
                "time",
                np.asarray(p_src, dtype="U16"),
                {
                    "long_name": "pressure source",
                    "description": "IGRA source code for pressure observations.",
                },
            ),

            "nonpressure_source": (
                "time",
                np.asarray(np_src, dtype="U16"),
                {
                    "long_name": "non-pressure source",
                    "description": "IGRA source code for non-pressure observations."
                },
            ),
        },
        coords={
            "time": pd.to_datetime(times),
            "level": np.arange(max_levels),
        },
        attrs={
            "source": "NOAA NCEI Integrated Global Radiosonde Archive (IGRA Version 2)",
            "institution": "NOAA National Centers for Environmental Information",
            "title": "IGRA Radiosonde Profiles",
            "history": (
                f"Converted from IGRA text format on "
                f"{pd.Timestamp.now().strftime('%Y-%m-%d %H:%M UTC')}"
            ),
            "references": (
                "https://www.ncei.noaa.gov/products/weather-balloon/integrated-global-radiosonde-archive"
                "integrated-global-radiosonde-archive"
            ),
            "featureType": "timeSeriesProfile",
        },
    )

    ds.attrs.update(attrs_dict)
    ds.attrs['station_name'] = ds.attrs['station_name'].title()
    ds.attrs['elevation_units'] = 'm'


    # Add header variables

    ds = xr.merge([ds, header_ds])

    ds = ds.drop_vars(['site_id', 'year', 'month', 'day', 'hour', 'latitude', 'longitude'])

    return ds

In [7]:
df, header = build_request(
    "BBM00078954",
    start_date="2020-07-18",
    end_date="2020-07-20",
    derived=False
)

ds = data_dataset(df, header)

In [8]:
ds

<xarray.Dataset> Size: 80kB
Dimensions:                   (time: 5, level: 131)
Coordinates:
  * time                      (time) datetime64[ns] 40B 2020-07-18 ... 2020-0...
  * level                     (level) int64 1kB 0 1 2 3 4 ... 127 128 129 130
Data variables: (12/19)
    lvltyp1                   (time, level) float64 5kB 2.0 1.0 2.0 ... 3.0 nan
    lvltyp2                   (time, level) float64 5kB 1.0 0.0 0.0 ... 0.0 nan
    etime                     (time, level) float64 5kB nan nan nan ... nan nan
    pressure                  (time, level) float64 5kB 1.008e+03 1e+03 ... nan
    pflag                     (time, level) float64 5kB 2.0 0.0 0.0 ... 0.0 nan
    height                    (time, level) float64 5kB nan 113.0 ... 3e+04 nan
    ...                        ...
    v_wind                    (time, level) float64 5kB -0.6 -0.4 ... 1.8 nan
    dewpoint                  (time, level) float64 5kB 23.2 22.5 ... nan nan
    release_time              (time) int64 40B 9000 4200 9000 4200 9000
    number_levels             (time) int64 40B 126 131 111 130 130
    pressure_source_code      (time) object 40B 'ncdc-gts' ... 'ncdc-gts'
    non_pressure_source_code  (time) object 40B 'ncdc-gts' ... 'ncdc-gts'

In [43]:
times = sorted(df["date"].unique())

header_data = header.copy()

header_data["date"] = pd.to_datetime(
    header_data[["year", "month", "day", "hour"]]
)

header_data = (
    header_data
    .set_index("date")
    .reindex(pd.to_datetime(times))
)

header_data.index.name = "time"

header_ds = xr.Dataset.from_dataframe(header_data)

In [44]:
header_ds.attrs['station_id'] = header_ds['site_id'].isel(time=-1).item()
header_ds.attrs['longitude'] = header_ds['longitude'].isel(time=-1).item()
header_ds.attrs['latitude'] = header_ds['latitude'].isel(time=-1).item()
header_ds.attrs['pressure_source_code'] = header_ds['pressure_source_code'].isel(time=-1).item()
header_ds.attrs['non_pressure_source_code'] = header_ds['non_pressure_source_code'].isel(time=-1).item()

header_ds = header_ds.drop_vars(['year', 'month', 'day', 'hour', 'site_id', 'longitude', 'latitude', 'pressure_source_code', 'non_pressure_source_code'])

header_ds

<xarray.Dataset> Size: 120B
Dimensions:        (time: 5)
Coordinates:
  * time           (time) datetime64[ns] 40B 2020-07-18 ... 2020-07-20
Data variables:
    release_time   (time) int64 40B 9000 4200 9000 4200 9000
    number_levels  (time) int64 40B 126 131 111 130 130
Attributes:
    station_id:                BBM00078954
    longitude:                 -59.4922
    latitude:                  13.0716
    pressure_source_code:      ncdc-gts
    non_pressure_source_code:  ncdc-gts

In [38]:
header_data

,site_id,year,month,day,hour,release_time,number_levels,pressure_source_code,non_pressure_source_code,latitude,longitude
time,,,,,,,,,,,
2020-07-18 00:00:00,BBM00078954,2020,7,18,0,9000,126,ncdc-gts,ncdc-gts,13.0716,-59.4922
2020-07-18 12:00:00,BBM00078954,2020,7,18,12,4200,131,ncdc-gts,ncdc-gts,13.0716,-59.4922
2020-07-19 00:00:00,BBM00078954,2020,7,19,0,9000,111,ncdc-gts,ncdc-gts,13.0716,-59.4922
2020-07-19 12:00:00,BBM00078954,2020,7,19,12,4200,130,ncdc-gts,ncdc-gts,13.0716,-59.4922
2020-07-20 00:00:00,BBM00078954,2020,7,20,0,9000,130,ncdc-gts,ncdc-gts,13.0716,-59.4922

In [35]:
header_ds['site_id'].isel(time=-1).item()

'BBM00078954'

In [2]:
from datetime import datetime
from typing import Optional

import numpy as np
import pandas as pd
from siphon.simplewebservice.igra2 import IGRAUpperAir
import xarray as xr

from src.sif.observations.igra2_requests import igra2_stations_df


def build_request(
    station_id: str,
    start_date: datetime | str,
    end_date: Optional[datetime | str] = None,
    derived: bool = False
) -> tuple[pd.DataFrame, pd.DataFrame]:

    start_date = pd.to_datetime(start_date)

    if end_date is None:
        dates = start_date

    else:
        end_date = pd.to_datetime(end_date)
        dates = [start_date, end_date]

    df, header = IGRAUpperAir.request_data(
        dates,
        station_id,
        derived=derived
    )

    if df.empty:

        if end_date is None:
            raise ValueError(
                f"No sounding found for station {station_id} "
                f"at {start_date:%Y-%m-%d %H:%M}."
            )

        else:
            raise ValueError(
                f"No soundings found for station {station_id} "
                f"between {start_date:%Y-%m-%d %H:%M} and "
                f"{end_date:%Y-%m-%d %H:%M}."
            )

    # Create a common datetime column in the header.
    header["date"] = pd.to_datetime(
        header[["year", "month", "day", "hour"]]
    )

    return df, header


def data_dataset(
    df_data: pd.DataFrame,
    header_data: pd.DataFrame
) \
        -> xr.Dataset:
    """
    Convert non-derived IGRA sounding data into an xarray Dataset.

    Parameters
    ----------
    df_data : pd.DataFrame
        IGRA sounding data returned by Siphon with derived=False.

    header_data : pd.DataFrame
        IGRA sounding header data.

    Returns
    -------
    xr.Dataset
        xarray Dataset containing the reported IGRA sounding profiles.
    """

    # Time and level dimensions.
    times = sorted(df_data["date"].unique())
    ntime = len(times)

    max_levels = df_data.groupby("date").size().max()
    levels = np.arange(max_levels)

    # Variables with vertical levels.
    profile_vars = [
        "pressure",
        "height",
        "temperature",
        "dewpoint",
        "relative_humidity",
        "direction",
        "speed",
        "u_wind",
        "v_wind",
        "lvltyp1",
        "lvltyp2",
        "etime",
    ]

    # Initialize arrays for profile variables with NaN values.
    arrays = {
        var: np.full((ntime, max_levels), np.nan)
        for var in profile_vars
    }

    # Per-sounding variables without vertical levels.
    release_time = np.full(ntime, np.nan)
    numlev = np.full(ntime, np.nan)
    lat = np.full(ntime, np.nan)
    lon = np.full(ntime, np.nan)

    p_src = []
    np_src = []

    # Loop through soundings
    for i, time in enumerate(times):

        sounding = df_data[df_data["date"] == time]

        n = len(sounding)

        # Fill profile arrays.
        for var in profile_vars:

            if var in sounding.columns:
                arrays[var][i, :n] = sounding[var].values

        # Get header information for this sounding.
        header = header_data[header_data["date"] == time]

        if len(header) > 0:

            header = header.iloc[0]

            release_time[i] = header["release_time"]
            numlev[i] = header["number_levels"]

            lat[i] = header["latitude"]
            lon[i] = header["longitude"]

            p_src.append(header["pressure_source_code"])
            np_src.append(header["non_pressure_source_code"])

        else:

            release_time[i] = np.nan
            numlev[i] = np.nan

            lat[i] = np.nan
            lon[i] = np.nan

            p_src.append("")
            np_src.append("")

    # ------------------------------------------------------------
    # Get station attributes
    # ------------------------------------------------------------

    station_id = header_data.iloc[0]["site_id"]

    station_df = igra2_stations_df()

    attrs_dict = (
        station_df.loc[
            station_df["station_id"] == station_id
        ]
        .reset_index(drop=True)
        .iloc[0]
        .to_dict()
    )

    # ------------------------------------------------------------
    # Construct Dataset
    # ------------------------------------------------------------

    ds = xr.Dataset(
        data_vars={

            # ----------------------------------------------------
            # Profile variables
            # ----------------------------------------------------

            "pressure": (
                ("time", "level"),
                arrays["pressure"],
                {
                    "long_name": "air pressure",
                    "standard_name": "air_pressure",
                    "units": "hPa",
                    "description": (
                        "Air pressure at the sounding level."
                    ),
                },
            ),

            "height": (
                ("time", "level"),
                arrays["height"],
                {
                    "long_name": "geopotential height",
                    "standard_name": "geopotential_height",
                    "units": "m",
                    "description": (
                        "Geopotential height of the sounding level."
                    ),
                },
            ),

            "temperature": (
                ("time", "level"),
                arrays["temperature"],
                {
                    "long_name": "air temperature",
                    "standard_name": "air_temperature",
                    "units": "degC",
                    "description": (
                        "Air temperature at the sounding level."
                    ),
                },
            ),

            "dewpoint": (
                ("time", "level"),
                arrays["dewpoint"],
                {
                    "long_name": "dew-point temperature",
                    "standard_name": "dew_point_temperature",
                    "units": "degC",
                    "description": (
                        "Dew-point temperature at the sounding level."
                    ),
                },
            ),

            "wind_dir": (
                ("time", "level"),
                arrays["direction"],
                {
                    "long_name": "wind direction",
                    "standard_name": "wind_from_direction",
                    "units": "degrees",
                    "description": (
                        "Direction from which the wind is blowing, "
                        "measured clockwise from true north."
                    ),
                },
            ),

            "wind_speed": (
                ("time", "level"),
                arrays["speed"],
                {
                    "long_name": "wind speed",
                    "standard_name": "wind_speed",
                    "units": "m/s",
                    "description": (
                        "Horizontal wind speed at the sounding level."
                    ),
                },
            ),

            "u_wind": (
                ("time", "level"),
                arrays["u_wind"],
                {
                    "long_name": "zonal wind component",
                    "standard_name": "eastward_wind",
                    "units": "m/s",
                    "description": (
                        "Eastward component of horizontal wind."
                    ),
                },
            ),

            "v_wind": (
                ("time", "level"),
                arrays["v_wind"],
                {
                    "long_name": "meridional wind component",
                    "standard_name": "northward_wind",
                    "units": "m/s",
                    "description": (
                        "Northward component of horizontal wind."
                    ),
                },
            ),

            "relative_humidity": (
                ("time", "level"),
                arrays["relative_humidity"],
                {
                    "long_name": "relative humidity",
                    "standard_name": "relative_humidity",
                    "units": "%",
                    "description": (
                        "Relative humidity at the sounding level."
                    ),
                },
            ),

            "lvltyp1": (
                ("time", "level"),
                arrays["lvltyp1"],
                {
                    "long_name": "primary level type",
                    "description": (
                        "IGRA primary level-type code."
                    ),
                },
            ),

            "lvltyp2": (
                ("time", "level"),
                arrays["lvltyp2"],
                {
                    "long_name": "secondary level type",
                    "description": (
                        "IGRA secondary level-type code."
                    ),
                },
            ),

            "etime": (
                ("time", "level"),
                arrays["etime"],
                {
                    "long_name": "elapsed time since launch",
                    "units": "s",
                    "description": (
                        "Elapsed time from radiosonde launch to "
                        "the observation at the sounding level."
                    ),
                },
            ),

            # Per-sounding variables
            "release_time": (
                "time",
                release_time,
                {
                    "long_name": "release time",
                    "units": "minutes",
                    "description": (
                        "Time of radiosonde release relative to "
                        "the nominal sounding time."
                    ),
                },
            ),

            "numlev": (
                "time",
                numlev,
                {
                    "long_name": "number of levels",
                    "units": "1",
                    "description": (
                        "Number of reported levels in the sounding."
                    ),
                },
            ),

            "latitude": (
                "time",
                lat,
                {
                    "long_name": "station latitude",
                    "standard_name": "latitude",
                    "units": "degrees_north",
                },
            ),

            "longitude": (
                "time",
                lon,
                {
                    "long_name": "station longitude",
                    "standard_name": "longitude",
                    "units": "degrees_east",
                },
            ),

            "pressure_source": (
                "time",
                np.asarray(p_src, dtype="U16"),
                {
                    "long_name": "pressure source",
                    "description": (
                        "IGRA source code for pressure observations."
                    ),
                },
            ),

            "nonpressure_source": (
                "time",
                np.asarray(np_src, dtype="U16"),
                {
                    "long_name": "non-pressure source",
                    "description": (
                        "IGRA source code for non-pressure observations."
                    ),
                },
            ),
        },

        coords={
            "time": pd.to_datetime(times),
            "level": levels,
        },

        attrs={
            "source": (
                "NOAA NCEI Integrated Global Radiosonde Archive "
                "(IGRA Version 2)"
            ),
            "institution": (
                "NOAA National Centers for Environmental Information"
            ),
            "title": "IGRA Radiosonde Profiles",
            "history": (
                f"Converted from IGRA data using Siphon on "
                f"{pd.Timestamp.now().strftime('%Y-%m-%d %H:%M UTC')}"
            ),
            "references": (
                "https://www.ncei.noaa.gov/products/weather-balloon/"
                "integrated-global-radiosonde-archive"
            ),
            "featureType": "timeSeriesProfile",
        },
    )

    # Add station metadata
    ds.attrs.update(attrs_dict)

    ds.attrs["station_name"] = (
        ds.attrs["station_name"].title()
    )

    ds.attrs["elevation_units"] = "m"

    return ds


def drvd_dataset(
    df_drvd: pd.DataFrame,
    header_drvd: pd.DataFrame
) \
        -> xr.Dataset:
    """
    Convert IGRA derived sounding data into an xarray Dataset.

    Parameters
    ----------
    df_drvd : pd.DataFrame
        IGRA derived sounding data returned by Siphon.

    header_drvd : pd.DataFrame
        IGRA derived sounding header data.

    Returns
    ----------
    xr.Dataset
        IGRA derived sounding parameters sorted chronologically.
    """

    # Sort chronologically
    times = sorted(df_drvd["date"].unique())
    ntime = len(times)

    max_levels = df_drvd.groupby("date").size().max()
    levels = np.arange(max_levels)

    profile_vars = [
        "pressure",
        "reported_geopotential_height",
        "calculated_geopotential_height",
        "temperature",
        "temperature_gradient",
        "potential_temperature",
        "potential_temperature_gradient",
        "virtual_temperature",
        "virtual_potential_temperature",
        "vapor_pressure",
        "saturation_vapor_pressure",
        "reported_relative_humidity",
        "calculated_relative_humidity",
        "relative_humidity_gradient",
        "u_wind",
        "u_wind_gradient",
        "v_wind",
        "v_wind_gradient",
        "refractive_index",
    ]

    # Initialize metadata arrays for profiles with NaN values. (e.g. pressure, temp)
    arrays = {
        var: np.full((ntime, max_levels), np.nan)
        for var in profile_vars
    }

    # Initialize metadata with one value per sounding. (e.g. lat, lon, launch time)
    pw = np.full(ntime, np.nan)

    inversion_pressure = np.full(ntime, np.nan)
    inversion_height = np.full(ntime, np.nan)

    mixed_layer_pressure = np.full(ntime, np.nan)
    mixed_layer_height = np.full(ntime, np.nan)

    freezing_pressure = np.full(ntime, np.nan)
    freezing_height = np.full(ntime, np.nan)

    lcl_pressure = np.full(ntime, np.nan)
    lcl_height = np.full(ntime, np.nan)

    lfc_pressure = np.full(ntime, np.nan)
    lfc_height = np.full(ntime, np.nan)

    lnb_pressure = np.full(ntime, np.nan)
    lnb_height = np.full(ntime, np.nan)

    lifted_index = np.full(ntime, np.nan)
    showalter_index = np.full(ntime, np.nan)
    k_index = np.full(ntime, np.nan)
    total_totals_index = np.full(ntime, np.nan)

    cape = np.full(ntime, np.nan)
    cin = np.full(ntime, np.nan)

    # Loop through soundings to fill arrays.
    for i, time in enumerate(times):

        sounding = df_drvd[df_drvd["date"] == time]

        n = len(sounding)

        # Fill the arrays.
        for var in profile_vars:

            if var in sounding.columns:
                arrays[var][i, :n] = sounding[var].values

        # Get header information for this sounding.
        header = header_drvd[header_drvd["date"] == time]

        if len(header) > 0:
            header = header.iloc[0]

            # Thermodynamic sounding parameters.
            pw[i] = header["precipitable_water"]

            inversion_pressure[i] = header["inv_pressure"]
            inversion_height[i] = header["inv_height"]

            mixed_layer_pressure[i] = header["mixed_layer_pressure"]
            mixed_layer_height[i] = header["mixed_layer_height"]

            freezing_pressure[i] = header["freezing_point_pressure"]
            freezing_height[i] = header["freezing_point_height"]

            lcl_pressure[i] = header["lcl_pressure"]
            lcl_height[i] = header["lcl_height"]

            lfc_pressure[i] = header["lfc_pressure"]
            lfc_height[i] = header["lfc_height"]

            lnb_pressure[i] = header["lnb_pressure"]
            lnb_height[i] = header["lnb_height"]

            # Stability indices.
            cape[i] = header["cape"]
            cin[i] = header["convective_inhibition"]

            lifted_index[i] = header["lifted_index"]
            showalter_index[i] = header["showalter_index"]

            k_index[i] = header["k_index"]
            total_totals_index[i] = header["total_totals_index"]


    # Get station metadata from the IGRA station list.
    station_id = header_drvd.iloc[0]["site_id"]

    station_df = igra2_stations_df()

    attrs_dict = station_df.loc[station_df["station_id"] == station_id].reset_index(drop=True).iloc[0].to_dict()


    ds = xr.Dataset(

        data_vars={

            # Profile variables

            "pressure": (
                ("time", "level"),
                arrays["pressure"],
                {
                    "long_name": "air pressure",
                    "standard_name": "air_pressure",
                    "units": "hPa",
                    "description": "Reported pressure at the sounding level.",
                },
            ),

            "reported_geopotential_height": (
                ("time", "level"),
                arrays["reported_geopotential_height"],
                {
                    "long_name": "reported geopotential height",
                    "standard_name": "geopotential_height",
                    "units": "m",
                    "description": "Reported geopotential height at the sounding level.",
                },
            ),

            "calculated_geopotential_height": (
                ("time", "level"),
                arrays["calculated_geopotential_height"],
                {
                    "long_name": "calculated geopotential height",
                    "standard_name": "geopotential_height",
                    "units": "m",
                    "description": (
                        "Geopotential height calculated using hydrostatic "
                        "balance where reported geopotential height is "
                        "unavailable."
                    ),
                },
            ),

            "temperature": (
                ("time", "level"),
                arrays["temperature"],
                {
                    "long_name": "air temperature",
                    "standard_name": "air_temperature",
                    "units": "K",
                    "description": (
                        "Reported air temperature at the sounding level."
                    ),
                },
            ),

            "temperature_gradient": (
                ("time", "level"),
                arrays["temperature_gradient"],
                {
                    "long_name": "vertical temperature gradient",
                    "units": "K km-1",
                    "description": (
                        "Temperature gradient between the current level "
                        "and the next higher level with a temperature "
                        "observation. Positive values indicate increasing "
                        "temperature with height."
                    ),
                },
            ),

            "potential_temperature": (
                ("time", "level"),
                arrays["potential_temperature"],
                {
                    "long_name": "potential temperature",
                    "standard_name": "air_potential_temperature",
                    "units": "K",
                    "description": "Potential temperature at the sounding level.",
                },
            ),

            "potential_temperature_gradient": (
                ("time", "level"),
                arrays["potential_temperature_gradient"],
                {
                    "long_name": "vertical potential temperature gradient",
                    "units": "K km-1",
                    "description": (
                        "Potential temperature gradient between the current "
                        "level and the next higher level with a potential "
                        "temperature observation. Positive values indicate "
                        "increasing potential temperature with height."
                    ),
                },
            ),

            "virtual_temperature": (
                ("time", "level"),
                arrays["virtual_temperature"],
                {
                    "long_name": "virtual temperature",
                    "standard_name": "virtual_temperature",
                    "units": "K",
                    "description": "Virtual temperature at the sounding level.",
                },
            ),

            "virtual_potential_temperature": (
                ("time", "level"),
                arrays["virtual_potential_temperature"],
                {
                    "long_name": "virtual potential temperature",
                    "standard_name": "virtual_potential_temperature",
                    "units": "K",
                    "description": "Virtual potential temperature at the sounding level.",
                },
            ),

            "vapor_pressure": (
                ("time", "level"),
                arrays["vapor_pressure"],
                {
                    "long_name": "water vapor pressure",
                    "standard_name": "water_vapor_partial_pressure_in_air",
                    "units": "hPa",
                    "description": (
                        "Vapor pressure calculated from temperature, "
                        "pressure, and dew-point depression."
                    ),
                },
            ),

            "saturation_vapor_pressure": (
                ("time", "level"),
                arrays["saturation_vapor_pressure"],
                {
                    "long_name": "saturation vapor pressure",
                    "standard_name": "water_vapor_saturation_pressure",
                    "units": "hPa",
                    "description": "Saturation vapor pressure calculated from pressure and temperature.",
                },
            ),

            "reported_relative_humidity": (
                ("time", "level"),
                arrays["reported_relative_humidity"],
                {
                    "long_name": "reported relative humidity",
                    "standard_name": "relative_humidity",
                    "units": "%",
                    "description": "Relative humidity reported in the original sounding.",
                },
            ),

            "calculated_relative_humidity": (
                ("time", "level"),
                arrays["calculated_relative_humidity"],
                {
                    "long_name": "calculated relative humidity",
                    "standard_name": "relative_humidity",
                    "units": "%",
                    "description": (
                        "Relative humidity calculated from vapor pressure, "
                        "saturation vapor pressure, and pressure."
                    ),
                },
            ),

            "relative_humidity_gradient": (
                ("time", "level"),
                arrays["relative_humidity_gradient"],
                {
                    "long_name": "vertical relative humidity gradient",
                    "units": "% km-1",
                    "description": (
                        "Relative humidity gradient between the current "
                        "level and the next higher usable level. Positive "
                        "values indicate increasing relative humidity "
                        "with height."
                    ),
                },
            ),

            "u_wind": (
                ("time", "level"),
                arrays["u_wind"],
                {
                    "long_name": "zonal wind component",
                    "standard_name": "eastward_wind",
                    "units": "m s-1",
                    "description": (
                        "Zonal wind component calculated from reported "
                        "wind speed and direction. Positive values are "
                        "eastward."
                    ),
                },
            ),

            "u_wind_gradient": (
                ("time", "level"),
                arrays["u_wind_gradient"],
                {
                    "long_name": "vertical zonal wind gradient",
                    "units": "m s-1 km-1",
                    "description": (
                        "Vertical gradient of the zonal wind component "
                        "between the current level and the next higher "
                        "level with a wind observation. Positive values "
                        "indicate that zonal wind becomes more positive "
                        "with height."
                    ),
                },
            ),

            "v_wind": (
                ("time", "level"),
                arrays["v_wind"],
                {
                    "long_name": "meridional wind component",
                    "standard_name": "northward_wind",
                    "units": "m s-1",
                    "description": (
                        "Meridional wind component calculated from reported "
                        "wind speed and direction. Positive values are "
                        "northward."
                    ),
                },
            ),

            "v_wind_gradient": (
                ("time", "level"),
                arrays["v_wind_gradient"],
                {
                    "long_name": "vertical meridional wind gradient",
                    "units": "m s-1 km-1",
                    "description": (
                        "Vertical gradient of the meridional wind component "
                        "between the current level and the next higher "
                        "level with a wind observation. Positive values "
                        "indicate that meridional wind becomes more positive "
                        "with height."
                    ),
                },
            ),

            "refractive_index": (
                ("time", "level"),
                arrays["refractive_index"],
                {
                    "long_name": "radio refractive index",
                    "units": "1",
                    "description": (
                        "Atmospheric refractive index at the sounding level."
                    ),
                },
            ),

            # Sounding-level parameters

            "pw": (
                "time",
                pw,
                {
                    "long_name": "precipitable water",
                    "standard_name": "atmosphere_water_vapor_content",
                    "units": "mm",
                    "description": "Precipitable water between the surface and 500 hPa.",
                },
            ),

            "inversion_pressure": (
                "time",
                inversion_pressure,
                {
                    "long_name": "inversion pressure",
                    "units": "Pa",
                    "description": (
                        "Pressure at the level of the warmest temperature "
                        "in the sounding when the warmest temperature "
                        "occurs above the surface."
                    ),
                },
            ),

            "inversion_height": (
                "time",
                inversion_height,
                {
                    "long_name": "inversion height",
                    "units": "m",
                    "description": "Height above the surface of the warmest temperature in the sounding.",
                },
            ),

            "mixed_layer_pressure": (
                "time",
                mixed_layer_pressure,
                {
                    "long_name": "mixed-layer top pressure",
                    "units": "Pa",
                    "description": "Pressure at the top of the mixed layer determined using the parcel method.",
                },
            ),

            "mixed_layer_height": (
                "time",
                mixed_layer_height,
                {
                    "long_name": "mixed-layer top height",
                    "units": "m",
                    "description": (
                        "Height above the surface of the top of the "
                        "mixed layer determined using the parcel method."
                    ),
                },
            ),

            "freezing_pressure": (
                "time",
                freezing_pressure,
                {
                    "long_name": "freezing-level pressure",
                    "units": "Pa",
                    "description": (
                        "Pressure where temperature first reaches the "
                        "freezing point when moving upward from the surface."
                    ),
                },
            ),

            "freezing_height": (
                "time",
                freezing_height,
                {
                    "long_name": "freezing-level height",
                    "units": "m",
                    "description": (
                        "Height above the surface where temperature first "
                        "reaches the freezing point."
                    ),
                },
            ),

            "lcl_pressure": (
                "time",
                lcl_pressure,
                {
                    "long_name": "lifting condensation level pressure",
                    "standard_name": "air_pressure_at_lifting_condensation_level",
                    "units": "Pa",
                    "description": "Pressure at the lifting condensation level.",
                },
            ),

            "lcl_height": (
                "time",
                lcl_height,
                {
                    "long_name": "lifting condensation level height",
                    "units": "m",
                    "description": "Height above the surface of the lifting condensation level.",
                },
            ),

            "lfc_pressure": (
                "time",
                lfc_pressure,
                {
                    "long_name": "level of free convection pressure",
                    "units": "Pa",
                    "description": "Pressure at the level of free convection.",
                },
            ),

            "lfc_height": (
                "time",
                lfc_height,
                {
                    "long_name": "level of free convection height",
                    "units": "m",
                    "description": "Height above the surface of the level of free convection.",
                },
            ),

            "lnb_pressure": (
                "time",
                lnb_pressure,
                {
                    "long_name": "level of neutral buoyancy pressure",
                    "units": "Pa",
                    "description": (
                        "Pressure at the level of neutral buoyancy, "
                        "also known as the equilibrium level."
                    ),
                },
            ),

            "lnb_height": (
                "time",
                lnb_height,
                {
                    "long_name": "level of neutral buoyancy height",
                    "units": "m",
                    "description": (
                        "Height above the surface of the level of "
                        "neutral buoyancy."
                    ),
                },
            ),

            # Stability indices

            "lifted_index": (
                "time",
                lifted_index,
                {
                    "long_name": "lifted index",
                    "units": "degC",
                    "description": "Lifted index calculated from the sounding.",
                },
            ),

            "showalter_index": (
                "time",
                showalter_index,
                {
                    "long_name": "Showalter index",
                    "units": "degC",
                    "description": (
                        "Showalter stability index calculated from "
                        "the sounding."
                    ),
                },
            ),

            "k_index": (
                "time",
                k_index,
                {
                    "long_name": "K index",
                    "units": "degC",
                    "description": (
                        "K index calculated from the sounding."
                    ),
                },
            ),

            "total_totals_index": (
                "time",
                total_totals_index,
                {
                    "long_name": "total totals index",
                    "units": "degC",
                    "description": (
                        "Total totals stability index calculated from "
                        "the sounding."
                    ),
                },
            ),

            "cape": (
                "time",
                cape,
                {
                    "long_name": "convective available potential energy",
                    "standard_name": "atmosphere_specific_convective_available_potential_energy",
                    "units": "J kg-1",
                    "description": (
                        "Convective available potential energy calculated "
                        "from the sounding."
                    ),
                },
            ),

            "cin": (
                "time",
                cin,
                {
                    "long_name": "convective inhibition",
                    "standard_name": "atmosphere_specific_convective_inhibition",
                    "units": "J kg-1",
                    "description": (
                        "Convective inhibition calculated from the sounding."
                    ),
                },
            ),
        },

        coords={
            "time": (
                "time",
                pd.to_datetime(times),
                {
                    "long_name": "sounding time",
                    "standard_name": "time",
                    "description": "Date and time of the radiosonde sounding.",
                },
            ),
            "level": (
                "level",
                np.arange(max_levels),
                {
                    "long_name": "sounding level",
                    "description": "Index of the vertical sounding levels.",
                },
            ),
        },

        attrs={
            "source": "NOAA NCEI Integrated Global Radiosonde Archive (IGRA Version 2)",
            "institution": "NOAA National Centers for Environmental Information",
            "title": "IGRA Derived Radiosonde Profiles",
            "history": (
                f"Converted from IGRA text format on "
                f"{pd.Timestamp.now().strftime('%Y-%m-%d %H:%M UTC')}"
            ),
            "references": (
                "https://www.ncei.noaa.gov/products/weather-balloon/integrated-global-radiosonde-archive"
                "integrated-global-radiosonde-archive"
            ),
            "featureType": "timeSeriesProfile"
        }

    )

    # Add station metadata.
    ds.attrs.update(attrs_dict)
    ds.attrs['station_name'] = ds.attrs['station_name'].title()
    ds.attrs['elevation_units'] = 'm'

    return ds


def merge_sounding_datasets(
        obs_ds: xr.Dataset,
        derived_ds: xr.Dataset
)\
        -> xr.Dataset:
    """Merges the observed profiles dataset and the derived indices dataset into a single dataset."""
    return xr.merge([obs_ds, derived_ds], compat="override", join='outer')


# Request data

df1, header1 = build_request(
    "BBM00078954",
    start_date="2020-07-18",
    end_date="2020-07-20",
    derived=False
)

df2, header2 = build_request(
    "BBM00078954",
    start_date="2020-07-18",
    end_date="2020-07-20",
    derived=True
)

# ================================================================
# Convert to xarray
# ================================================================

ds1 = data_dataset(df1, header1)
ds2 = drvd_dataset(df2, header2)

ds = merge_sounding_datasets(ds1, ds2)

In [3]:
ds

<xarray.Dataset> Size: 144kB
Dimensions:                         (time: 5, level: 131)
Coordinates:
  * time                            (time) datetime64[ns] 40B 2020-07-18 ... ...
  * level                           (level) int64 1kB 0 1 2 3 ... 128 129 130
Data variables: (12/52)
    pressure                        (time, level) float64 5kB 1.008e+03 ... nan
    height                          (time, level) float64 5kB nan 113.0 ... nan
    temperature                     (time, level) float64 5kB 28.2 27.2 ... nan
    dewpoint                        (time, level) float64 5kB 23.2 22.5 ... nan
    wind_dir                        (time, level) float64 5kB 80.0 85.0 ... nan
    wind_speed                      (time, level) float64 5kB 3.6 4.1 ... nan
    ...                              ...
    lifted_index                    (time) float64 40B -4.0 -1.0 -2.0 -3.0 0.0
    showalter_index                 (time) float64 40B 2.0 7.0 3.0 4.0 4.0
    k_index                         (time) float64 40B 24.0 24.0 23.0 19.0 20.0
    total_totals_index              (time) float64 40B 42.0 35.0 39.0 38.0 38.0
    cape                            (time) float64 40B 2.809e+03 ... 689.0
    cin                             (time) float64 40B -3.0 -12.0 0.0 0.0 -22.0
Attributes: (12/16)
    source:               NOAA NCEI Integrated Global Radiosonde Archive (IGR...
    institution:          NOAA National Centers for Environmental Information
    title:                IGRA Radiosonde Profiles
    history:              Converted from IGRA data using Siphon on 2026-09-21...
    references:           https://www.ncei.noaa.gov/products/weather-balloon/...
    featureType:          timeSeriesProfile
    ...                   ...
    state:                nan
    station_name:         Grantley Adams
    first_year:           1965
    last_year:            2026
    number_of_soundings:  32459
    elevation_units:      m

In [2]:
ds1

<xarray.Dataset> Size: 65kB
Dimensions:             (time: 5, level: 131)
Coordinates:
  * time                (time) datetime64[ns] 40B 2020-07-18 ... 2020-07-20
  * level               (level) int64 1kB 0 1 2 3 4 5 ... 126 127 128 129 130
Data variables: (12/18)
    pressure            (time, level) float64 5kB 1.008e+03 1e+03 ... nan nan
    height              (time, level) float64 5kB nan 113.0 nan ... 3e+04 nan
    temperature         (time, level) float64 5kB 28.2 27.2 27.2 ... nan nan nan
    dewpoint            (time, level) float64 5kB 23.2 22.5 22.7 ... nan nan nan
    wind_dir            (time, level) float64 5kB 80.0 85.0 nan ... 95.0 nan
    wind_speed          (time, level) float64 5kB 3.6 4.1 nan ... 23.7 21.1 nan
    ...                  ...
    release_time        (time) float64 40B 9e+03 4.2e+03 9e+03 4.2e+03 9e+03
    numlev              (time) float64 40B 126.0 131.0 111.0 130.0 130.0
    latitude            (time) float64 40B 13.07 13.07 13.07 13.07 13.07
    longitude           (time) float64 40B -59.49 -59.49 -59.49 -59.49 -59.49
    pressure_source     (time) <U16 320B 'ncdc-gts' 'ncdc-gts' ... 'ncdc-gts'
    nonpressure_source  (time) <U16 320B 'ncdc-gts' 'ncdc-gts' ... 'ncdc-gts'
Attributes: (12/16)
    source:               NOAA NCEI Integrated Global Radiosonde Archive (IGR...
    institution:          NOAA National Centers for Environmental Information
    title:                IGRA Radiosonde Profiles
    history:              Converted from IGRA data using Siphon on 2026-09-17...
    references:           https://www.ncei.noaa.gov/products/weather-balloon/...
    featureType:          timeSeriesProfile
    ...                   ...
    state:                nan
    station_name:         Grantley Adams
    first_year:           1965
    last_year:            2026
    number_of_soundings:  32453
    elevation_units:      m

In [12]:
ds2

<xarray.Dataset> Size: 42kB
Dimensions:                         (time: 5, level: 54)
Coordinates:
  * time                            (time) datetime64[ns] 40B 2020-07-18 ... ...
  * level                           (level) int64 432B 0 1 2 3 4 ... 50 51 52 53
Data variables: (12/38)
    pressure                        (time, level) float64 2kB 1.008e+03 ... 11.7
    reported_geopotential_height    (time, level) float64 2kB nan nan ... nan
    calculated_geopotential_height  (time, level) float64 2kB nan nan ... nan
    temperature                     (time, level) float64 2kB 301.4 ... 226.7
    temperature_gradient            (time, level) float64 2kB -15.2 0.0 ... nan
    potential_temperature           (time, level) float64 2kB 300.7 ... 808.3
    ...                              ...
    lifted_index                    (time) float64 40B -4.0 -1.0 -2.0 -3.0 0.0
    showalter_index                 (time) float64 40B 2.0 7.0 3.0 4.0 4.0
    k_index                         (time) float64 40B 24.0 24.0 23.0 19.0 20.0
    total_totals_index              (time) float64 40B 42.0 35.0 39.0 38.0 38.0
    cape                            (time) float64 40B 2.809e+03 ... 689.0
    cin                             (time) float64 40B -3.0 -12.0 0.0 0.0 -22.0
Attributes: (12/16)
    source:               NOAA NCEI Integrated Global Radiosonde Archive (IGR...
    institution:          NOAA National Centers for Environmental Information
    title:                IGRA Derived Radiosonde Profiles
    history:              Converted from IGRA text format on 2026-09-17 14:40...
    references:           https://www.ncei.noaa.gov/products/weather-balloon/...
    featureType:          timeSeriesProfile
    ...                   ...
    state:                nan
    station_name:         Grantley Adams
    first_year:           1965
    last_year:            2026
    number_of_soundings:  32453
    elevation_units:      m

In [14]:
ds

<xarray.Dataset> Size: 144kB
Dimensions:                         (time: 5, level: 131)
Coordinates:
  * time                            (time) datetime64[ns] 40B 2020-07-18 ... ...
  * level                           (level) int64 1kB 0 1 2 3 ... 128 129 130
Data variables: (12/52)
    pressure                        (time, level) float64 5kB 1.008e+03 ... nan
    height                          (time, level) float64 5kB nan 113.0 ... nan
    temperature                     (time, level) float64 5kB 28.2 27.2 ... nan
    dewpoint                        (time, level) float64 5kB 23.2 22.5 ... nan
    wind_dir                        (time, level) float64 5kB 80.0 85.0 ... nan
    wind_speed                      (time, level) float64 5kB 3.6 4.1 ... nan
    ...                              ...
    lifted_index                    (time) float64 40B -4.0 -1.0 -2.0 -3.0 0.0
    showalter_index                 (time) float64 40B 2.0 7.0 3.0 4.0 4.0
    k_index                         (time) float64 40B 24.0 24.0 23.0 19.0 20.0
    total_totals_index              (time) float64 40B 42.0 35.0 39.0 38.0 38.0
    cape                            (time) float64 40B 2.809e+03 ... 689.0
    cin                             (time) float64 40B -3.0 -12.0 0.0 0.0 -22.0
Attributes: (12/16)
    source:               NOAA NCEI Integrated Global Radiosonde Archive (IGR...
    institution:          NOAA National Centers for Environmental Information
    title:                IGRA Radiosonde Profiles
    history:              Converted from IGRA data using Siphon on 2026-09-17...
    references:           https://www.ncei.noaa.gov/products/weather-balloon/...
    featureType:          timeSeriesProfile
    ...                   ...
    state:                nan
    station_name:         Grantley Adams
    first_year:           1965
    last_year:            2026
    number_of_soundings:  32453
    elevation_units:      m